# Generated by Django 5.2.12 on 2026-04-07 04:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_table',
            old_name='login',
            new_name='Login',
        ),
        migrations.AddField(
            model_name='food_table',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leftover_foodtable',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 4, 7, 9, 47, 0, 302432)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_table',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
    ]
