# Generated by Django 5.2.12 on 2026-04-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_login_user_table_login_food_table_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_table',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
