# Generated by Django 5.2.12 on 2026-04-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hotel_table_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leftover_order_table',
            old_name='quality',
            new_name='quantity',
        ),
    ]
