# Generated by Django 5.2.12 on 2026-04-17 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_quality_leftover_order_table_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftover_order_table',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 17, 12, 7, 47, 426010)),
            preserve_default=False,
        ),
    ]
