# Generated by Django 5.2.12 on 2026-04-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_leftover_order_table_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint_table',
            old_name='user',
            new_name='USER',
        ),
        migrations.RenameField(
            model_name='food_table',
            old_name='hotel',
            new_name='HOTEL',
        ),
        migrations.RenameField(
            model_name='hotel_table',
            old_name='Login',
            new_name='LOGIN',
        ),
        migrations.RenameField(
            model_name='leftover_foodtable',
            old_name='food',
            new_name='FOOD',
        ),
        migrations.RenameField(
            model_name='leftover_order_table',
            old_name='left',
            new_name='LEFT',
        ),
        migrations.RenameField(
            model_name='leftover_order_table',
            old_name='user',
            new_name='USER',
        ),
        migrations.RenameField(
            model_name='order_table',
            old_name='food',
            new_name='FOOD',
        ),
        migrations.RenameField(
            model_name='order_table',
            old_name='user',
            new_name='USER',
        ),
        migrations.RenameField(
            model_name='user_table',
            old_name='Login',
            new_name='LOGIN',
        ),
    ]
